# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: Titaniam

stages:
- stage: Build
  displayName: Build Java project
  jobs:
  - job: Build
    displayName: Build Maven Project
    steps:
      - task: Maven@4
        inputs:
          mavenPomFile: 'pom.xml'
          publishJUnitResults: false
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false
  # - job: Docker
  #   displayName: Create Docker Image
  #   steps:
  #     - task: Maven@4
  #       inputs:
  #         mavenPomFile: 'pom.xml'
  #         publishJUnitResults: false
  #         javaHomeOption: 'JDKVersion'
  #         mavenVersionOption: 'Default'
  #         mavenAuthenticateFeed: false
  #         effectivePomSkip: false
  #         sonarQubeRunAnalysis: false
      
